---
queries:
  - name: device_info
    file_path: "templates/device_info.gql"

jinja2_transforms:
  - name: "device_eos"
    description: "Arista EOS Template"
    query: "device_info"
    template_path: templates/device_arista_eos_config.tpl.j2
